name: Nextflow Check

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  nextflow-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nextflow latest-edge
        uses: nf-core/setup-nextflow@v1
        with:
          version: "latest-edge"

      - name: Check Nextflow syntax
        run: nextflow inspect main.nf
        # TODO: we want to run a linter as well??